services:
  mysql:
    image: mysql:8.0
    container_name: rentas_mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: Password!
      TZ: America/Mexico_City
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
